networks:
  fooddelivery-net:
    driver: bridge
    name: fooddelivery-net

services:
  ###################################
  # Customer: The Customer microservice
  ###################################
  customer:
    build:
      context: ./customer/
      dockerfile: customer.Dockerfile
    image: fooddelivery/customer:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/fooddelivery1
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"
    networks:
      - fooddelivery-net

  ###################################
  # Restaurant: The Restaurant microservice
  ###################################
  restaurant:
    build:
      context: ./restaurant/
      dockerfile: restaurant.Dockerfile
    image: fooddelivery/restaurant:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/fooddelivery1
      PYTHONUNBUFFERED: 1
    ports:
      - "5007:5007"
    networks:
      - fooddelivery-net

  ###################################
  # Restaurant Inventory: The Restaurant Inventory microservice
  ###################################
  restaurant_inventory:
    build:
      context: ./restaurant_inventory/
      dockerfile: restaurant_inventory.Dockerfile
    image: fooddelivery/restaurant_inventory:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/fooddelivery1
      PYTHONUNBUFFERED: 1
    ports:
      - "5008:5008"
    networks:
      - fooddelivery-net

  ###################################
  # Transaction: The Transaction microservice
  ###################################
  transaction:
    build:
      context: ./transaction/
      dockerfile: transaction.Dockerfile
    image: fooddelivery/transaction:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/fooddelivery1
      PYTHONUNBUFFERED: 1
    ports:
      - "5009:5009"
    networks:
      - fooddelivery-net

  ###################################
  # Transaction Item: The Transaction Item microservice
  ###################################
  transaction_item:
    build:
      context: ./transaction_item/
      dockerfile: transaction_item.Dockerfile
    image: fooddelivery/transaction_item:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/fooddelivery1
      PYTHONUNBUFFERED: 1
    ports:
      - "5010:5010"
    networks:
      - fooddelivery-net

  ###################################
  # Notification: The Notification microservice
  ###################################
  notification:
    build:
      context: ./notification/
      dockerfile: notification.Dockerfile
    image: fooddelivery/notification:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/fooddelivery1
      PYTHONUNBUFFERED: 1
    ports:
      - "5011:5011"
    networks:
      - fooddelivery-net

  ###################################
  # Voucher: The Voucher microservice
  ###################################
  voucher:
    build:
      context: ./voucher/
      dockerfile: voucher.Dockerfile
    image: fooddelivery/voucher:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/fooddelivery1
      PYTHONUNBUFFERED: 1
    ports:
      - "5012:5012"
    networks:
      - fooddelivery-net

  
  ###################################
  # Personalized Homepage: The composite microservice
  ###################################
  displayPersonalizedHomepage:
    build:
      context: ./displayPersonalizedHomepage/
      dockerfile: displayPersonalizedHomepage.Dockerfile
    image: fooddelivery/personalized_homepage:latest
    restart: always
    environment:
      customer_URL: "http://customer:5006/customer"
      restaurant_URL: "http://restaurant:5007/restaurant"
      restaurant_inventory_URL: "http://restaurant_inventory:5008/restaurant_inventory"
      transaction_URL: "http://transaction:5009/transaction"
      transaction_item_URL: "http://transaction_item:5010/transaction_item"
      notification_URL: "http://notification:5011/notification"
      voucher_URL: "http://voucher:5012/voucher"
      PYTHONUNBUFFERED: 1
    ports:
      - "5013:5013"
    networks:
      - fooddelivery-net
    depends_on:
      - customer
      - restaurant
      - restaurant_inventory
      - transaction
      - transaction_item
      - notification
      - voucher